export enum ErrorCode {
  SUCCESS,
  MESSAGE_NOT_DEFINED,
  CONNECTION_NOT_ESTABLISHED,
  FAILED_TO_SEND_MESSAGE,
  MESSAGE_INVALID,
  MESSAGE_INVALID_DURATION_MILLIS,

  MESSAGE_INVALID_DOT_INDEX_HEAD,
  MESSAGE_INVALID_DOT_INDEX_ARM,
  MESSAGE_INVALID_DOT_INDEX_VEST,

  MESSAGE_INVALID_INTENSITY,
  MESSAGE_INVALID_X,
  MESSAGE_INVALID_Y,
  MESSAGE_INVALID_ROTATION_X,
  MESSAGE_INVALID_ROTATION_Y,
  MESSAGE_INVALID_SCALE_INTENSITY_RATIO,
  MESSAGE_INVALID_SCALE_DURATION_RATIO,
  MESSAGE_NOT_REGISTERED_KEY,
  MESSAGE_NOT_INITIALIZED,
}

export default ErrorCode;
